import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Bell, BellOff, Building2, Hash, Target } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { PageHeader, SectionHeader, Tag, ageLabel } from "@/components/scout/primitives";
import { listFollows, listNotifications } from "@/lib/api/client";

export const Route = createFileRoute("/following")({
  head: () => ({
    meta: [
      { title: "Following & Alerts — Digital Scout" },
      {
        name: "description",
        content:
          "Topics, needs and companies you follow, plus the AI alerts Digital Scout raises when new matches, reports or external signals appear.",
      },
      { property: "og:title", content: "Following & Alerts — Digital Scout" },
      {
        property: "og:description",
        content: "Stay informed on the technology areas you care about without chasing updates.",
      },
    ],
  }),
  component: FollowingPage,
});

const ICON = { need: Target, company: Building2, topic: Hash, project: Target };

function FollowingPage() {
  const { data: follows = [] } = useQuery({ queryKey: ["follows"], queryFn: listFollows });
  const { data: notifications = [] } = useQuery({
    queryKey: ["notifications"],
    queryFn: listNotifications,
  });

  return (
    <div className="mx-auto max-w-[1100px] px-5 py-6 lg:px-8">
      <PageHeader
        eyebrow="Personalisation"
        title="Following and alerts"
        description="Digital Scout watches your topics continuously and tells you when something changes."
      />

      <div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
        <section>
          <SectionHeader title="Alerts" description="Generated by the monitoring agents." />
          <div className="panel divide-y divide-border">
            {notifications.map((n) => {
              const href =
                n.entityType === "need"
                  ? `/needs/${n.entityId}`
                  : n.entityType === "company"
                    ? `/companies/${n.entityId}`
                    : n.entityType === "project"
                      ? "/projects"
                      : `/knowledge?doc=${n.entityId}`;
              return (
                <a key={n.id} href={href} className="block px-4 py-3.5 hover:bg-muted/50">
                  <div className="flex items-start gap-3">
                    <Bell className={`mt-0.5 size-4 shrink-0 ${n.read ? "text-muted-foreground" : "text-primary"}`} />
                    <div className="min-w-0 flex-1">
                      <p className="text-[13px] font-semibold text-foreground">{n.title}</p>
                      <p className="mt-0.5 text-[12.5px] leading-relaxed text-muted-foreground">{n.body}</p>
                      <p className="mt-1 text-[11px] text-muted-foreground">
                        {n.kind} · {ageLabel(n.at)}
                      </p>
                    </div>
                    {!n.read ? <span className="mt-1.5 size-2 shrink-0 rounded-full bg-primary" /> : null}
                  </div>
                </a>
              );
            })}
          </div>
        </section>

        <aside>
          <SectionHeader title="Following" description={`${follows.length} subscriptions`} />
          <div className="panel divide-y divide-border">
            {follows.map((f) => {
              const Icon = ICON[f.type];
              return (
                <div key={f.id} className="flex items-start gap-3 px-4 py-3">
                  <Icon className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
                  <div className="min-w-0 flex-1">
                    <p className="text-[12.5px] font-medium leading-snug text-foreground">{f.label}</p>
                    <p className="text-[11.5px] text-muted-foreground">{f.meta}</p>
                    <p className="mt-0.5 text-[11px] text-muted-foreground">Following since {ageLabel(f.since)}</p>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 px-2"
                    onClick={() => toast.success(`Unfollowed ${f.label}`)}
                  >
                    <BellOff className="size-3.5" />
                  </Button>
                </div>
              );
            })}
          </div>

          <div className="panel mt-4 p-4">
            <p className="text-[13px] font-semibold text-foreground">Digest settings</p>
            <div className="mt-2 space-y-1.5 text-[12.5px]">
              {[
                ["Weekly digest", "Monday 07:00, Houston time"],
                ["New company matches", "Immediate"],
                ["Field reports", "Immediate"],
                ["Stale need reminders", "Every 30 days"],
              ].map(([k, v]) => (
                <div key={k} className="flex justify-between gap-3">
                  <span className="text-muted-foreground">{k}</span>
                  <Tag>{v}</Tag>
                </div>
              ))}
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
