/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as NeedsIndexRouteImport } from './routes/needs.index'
import { Route as NeedsNeedIdRouteImport } from './routes/needs.$needId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsIndexRoute = NeedsIndexRouteImport.update({
  id: '/needs/',
  path: '/needs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsNeedIdRoute = NeedsNeedIdRouteImport.update({
  id: '/needs/$needId',
  path: '/needs/$needId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/needs/$needId': typeof NeedsNeedIdRoute
  '/needs/': typeof NeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/needs/$needId': typeof NeedsNeedIdRoute
  '/needs': typeof NeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/needs/$needId': typeof NeedsNeedIdRoute
  '/needs/': typeof NeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/needs/$needId' | '/needs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/needs/$needId' | '/needs'
  id: '__root__' | '/' | '/ask' | '/needs/$needId' | '/needs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  NeedsNeedIdRoute: typeof NeedsNeedIdRoute
  NeedsIndexRoute: typeof NeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/': {
      id: '/needs/'
      path: '/needs'
      fullPath: '/needs/'
      preLoaderRoute: typeof NeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/$needId': {
      id: '/needs/$needId'
      path: '/needs/$needId'
      fullPath: '/needs/$needId'
      preLoaderRoute: typeof NeedsNeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  NeedsNeedIdRoute: NeedsNeedIdRoute,
  NeedsIndexRoute: NeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
